### ISSUE TITLE
API 테스트 요청 드립니다

### ISSUE THREAD

**Issue by DevelopDestroyer** [DevelopDestroyer/WooriPickXXX#1]
@PeterJSung 
회원가입 API를 테스트용으로 만들어두었습니다. 
아래 내용을 12일 전까지 체크해둔다면 원활하게 개발, 협업을 할 수 있을것 같습니다
1. 추후 개발 및 테스트를 위해 로컬환경에 스프링 빌드가 가능한 상태 만들기
2. 프론트단에서 axios를 통해 아래 API가 request/response가 정상인지 확인

* API 기능
멤버 등록 기능(회원가입)

* URL 정보
[POST] https://localhost:8000/api/members

* 요청 파라미터
name, phoneNumber, password
`{
    "name": "이재용",
    "phoneNumber": "010-5018-1235",
    "password": "000000"
}`

* 정상 멤버 가입처리
![image](https://user-images.githubusercontent.com/20551424/114265529-3c8c5380-9a2c-11eb-953d-ba205bf80030.png)
`{
    "statusCode": "OK",
    "message": "SUCCESS",
    "data": {
        "name": "이재용",
        "id": 6,
        "phoneNumber": "010-5018-1235"
    }
}`

* 이미 존재하는 멤버 예외처리
![image](https://user-images.githubusercontent.com/20551424/114265511-1ff01b80-9a2c-11eb-8df2-44942b54b35e.png)
`{
    "statusCode": "FAIL",
    "message": "동일한 이메일이 존재합니다.",
    "errorCode": "U003"
}`

감사합니다.

**Comment by PeterJSung** [comment]
git hash 9f64772b035db094f5206244c31989948fb03670 반영 완료. 
![image](https://user-images.githubusercontent.com/14996546/114274676-9c99ee80-9a5a-11eb-8d9a-bc0231d3ee29.png)

**Comment by DevelopDestroyer** [comment]
확인되어 이슈를 닫습니다
