### ISSUE TITLE
react 빌드 산출물 경로

### ISSUE THREAD

**Issue by DevelopDestroyer** [DevelopDestroyer/WooriPickXXX#2]
@PeterJSung 

React 빌드 후 생성돼는 결과물(index.html을 포함한 그 외 리소스)은 아래 경로에 위치하면 됩니다.
현재 테스트 페이지를 넣어두었으니 갈아엎어두 상관 없습니다. :) 
WooriPickXXX/back/src/main/resources/static

![image](https://user-images.githubusercontent.com/20551424/114266006-de14a480-9a2e-11eb-87f1-b944feccbcbf.png)

**Comment by PeterJSung** [comment]
git hash 9f64772b035db094f5206244c31989948fb03670 반영 완료. front 폴더에서 npm run build-spring-bin 구문 실행

**Comment by DevelopDestroyer** [comment]
@PeterJSung static 디렉터리에 내용이 없는것으로 확인이 되고있는데, 개발편의를 위해 commit/push할때 포함 부탁드립니다

**Comment by PeterJSung** [comment]
완료함. front 에서 commit 할때 wooriPick 폴더에서 commit 시 정상적으로 동작함.

**Comment by DevelopDestroyer** [comment]
이슈 닫습니다~
